name: daum_postcode_view
description: Daum Postcode View Service for Flutter
version: 0.1.0
homepage: https://github.com/onehunnitconst/daum_postcode_view

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  webview_flutter: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.6.2

flutter:

